drop "Redirect to a Shortened URL"
ietf-wg-gnap/gnap-core-protocol pull request #139
Opened 2020-12-03 23:18 UTC by aaronpk

closes #121

2020-12-04 14:56 UTC, jricher requested changes
The same change needs to be made in the appendix under "Secondary Device Interaction {#example-device}". 

One of these examples can keep the redirection as an option alongside the user code, just not the shortened form.

2020-12-04 14:56 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +display a [user code](#request-interact-usercode), but it cannot accept a callback.
This example can keep the redirection piece, just not the shortened form.

```suggestion
display a [user code](#request-interact-usercode) and direct the RQ
to an [arbitrary URL](#request-interact-redirect) on a secondary
device, but it cannot accept a callback.
```

2020-12-04 14:56 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
>      "interact": {
```suggestion
    "interact": {
        "redirect": true,
```

2020-12-04 15:09 UTC, aaronpk commented
Thanks, I missed that!

2020-12-16 19:27 UTC, jricher approved these changes

2020-12-23 15:51 UTC, merged