closing issue 98, effectively removing section 5.4
ietf-wg-gnap/gnap-core-protocol pull request #170
Opened 2021-02-08 17:22 UTC by fimbault

- Reading the state of a request (#98) - editorial change removes section 5.1
- Updating and reading access tokens (#99) 
- Remove the links to already closed issues in the spec (issues #29, #55, #106, #98, #99)
- Update the list of high level changes for upcoming version 4

2021-02-08 18:45 UTC, yaronf commented
Guys, please don't mix editorial and technical commits in the same PR. 😢

2021-02-08 19:00 UTC, jricher commented
@yaronf this does not mix those types. This is a removal of a section that was marked for removal several months ago and has received no input to keep it, after several requests by the editors.

2021-02-08 19:31 UTC, jricher commented
On second read, I realize I missed a change and I agree with Yaron: this PR should not remove issue links to unrelated issues. Those should be in a separate PR.

2021-02-08 19:32 UTC, jricher requested changes
This PR should only close the links for only the affected issues. A cleanup PR should be added separately as needed.

2021-02-09 07:54 UTC, fimbault commented
Change done, only 98 and 99 are now concerned.

2021-02-09 12:16 UTC, jricher requested changes
just needs the changelog updated (included) and otherwise looks good

2021-02-09 12:16 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +    - Closed issues related to reading and updating access tokens
```suggestion
    - Removed function to read state of grant request by client
    - Closed issues related to reading and updating access tokens
```

2021-02-09 12:39 UTC, fimbault commented on draft-ietf-gnap-core-protocol.md
> +    - Closed issues related to reading and updating access tokens
yes that's clearer, done

2021-02-09 13:28 UTC, jricher approved these changes

2021-02-10 15:17 UTC, davidgtonge commented
I'm a bit late as this has already been approved. I'm ok with the text being removed, but I do think we need to address https://github.com/ietf-wg-gnap/gnap-core-protocol/issues/146

2021-02-18 12:01 UTC, merged