add role diagram
ietf-wg-gnap/gnap-core-protocol pull request #267
Opened 2021-06-08 21:50 UTC by aaronpk

adds a diagram illustrating the relationship between the roles in GNAP

for #217

2021-06-10 12:08 UTC, jricher requested changes
Diagram itself is OK I think, but the line/arrow style is different from the other diagrams in the doc (this one seems to use higher ASCII/ANSI line characters instead of low-ASCII?). I'm fine with either but I think it should be consistent.

2021-06-10 12:08 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +       +       │  Client  │
Do we want this to be a "client instance" instead?

2021-06-11 20:42 UTC, aaronpk commented
Replaced with ascii chars!

2021-06-11 21:17 UTC, jricher approved these changes

2021-06-15 13:15 UTC, yaronf commented
We have been using the "goat" tool in one of my drafts to convert ASCII art to SVG. The results are very nice. You may want to consider this option.

* Tool: https://github.com/blampe/goat
* Makefile: https://github.com/yaronf/I-D/blob/main/STAR-Delegation/Makefile
* Source ASCII art: https://github.com/yaronf/I-D/tree/main/STAR-Delegation/art
* Plaintext rendering: https://www.ietf.org/archive/id/draft-ietf-acme-star-delegation-09.txt (see e.g. Fig. 11)
* HTML+SVG rendering: https://www.ietf.org/archive/id/draft-ietf-acme-star-delegation-09.html

2021-06-23 15:25 UTC, merged