trim dpop
ietf-wg-gnap/gnap-core-protocol pull request #271
Opened 2021-07-05 15:01 UTC by fimbault

remove OAuth DPoP binding. Described why on IETF mailing list: 
only works for asymmetric keys, requires key be presented in the header (duplicating information from GNAP messages). It was never meant to be a general purpose signing mechanism, though the FAPI group in OIDF is considering it as an option in current proposed work.

2021-07-06 19:06 UTC, jricher requested changes
This PR has a lot of spurious formatting changes, including a number of things that break the YAML header at the start of the file. It looks like your editor might have auto-formatted the text? Please re-submit with only the intended changes.

2021-07-07 15:01 UTC, fimbault commented
Ok that's weird (just removed some lines...), will have a look

2021-07-11 09:39 UTC, fimbault commented
Ok that was due to my rust analyser in vscode, fixed it now

2021-07-11 12:50 UTC, jricher approved these changes

2021-07-12 14:14 UTC, merged