refactor token response details to use flags array
ietf-wg-gnap/gnap-core-protocol pull request #273
Opened 2021-07-07 20:34 UTC by aaronpk

...to match the flags array in the token request.

While this is technically a breaking change, I think we should consider this editorial as this should have been changed when we made the original change to use a flags array in the request in #162.

2021-07-07 20:45 UTC, jricher requested changes
Looks good - the two "bound" examples in the general response section need to be updated with the flag syntax. Nit: I'd recommend putting strings around the values for the flag definitions in the token request/response like we do in the interaction section. I added suggestions for the response but couldn't make suggestions for the request since it wasn't edited here.

2021-07-07 20:45 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +bearer
```suggestion
"bearer"
```

2021-07-07 20:45 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +durable
```suggestion
"durable"
```

2021-07-07 20:45 UTC, jricher commented on draft-ietf-gnap-core-protocol.md
> +split
```suggestion
"split"
```

2021-07-07 20:58 UTC, aaronpk commented
> Nit: I'd recommend putting strings around the values for the flag definitions in the token request/response like we do in the interaction section. I added suggestions for the response but couldn't make suggestions for the request since it wasn't edited here.

You know, I had that thought, and I checked the request section and it doesn't have quotes. I'm going to add the quotes to both parts.

> Looks good - the two "bound" examples in the general response section need to be updated with the flag syntax.

This ended up with some other language changing, not just the examples, so let me know what you think.

2021-07-08 10:19 UTC, jricher approved these changes

2021-07-12 14:17 UTC, merged